"""Backfill REIWA suburb price snapshots via the Wayback Machine.

Fetches archived versions of ``https://prpub.reiwa.com.au/suburb/<slug>/``
for a user-specified date range (monthly cadence), parses the embedded
``data-props`` JSON payload and writes a long-form history table.

Requirements
------------
- Archived pages must exist on the Wayback Machine. Not every suburb/month
  combination is guaranteed to have a capture.
- ``data_raw/reiwa_suburbs.csv`` (slug, suburb_name, state) – generated by
  ``python -m src.cli build-reiwa-suburbs``.
- ``data_raw/ssc_to_sa2_2021.csv`` (SAL→SA2 mapping with allocation_ratio)
  to estimate suburb population.
- An ABS population table (SA2 level) that includes 2023 population counts.
  Provide the path via ``--population-csv`` (must contain columns
  ``sa2_code`` and ``population``).

Usage
-----
  python -m tools.fetch_reiwa_wayback \
      --start 2023-01 --end 2025-09 \
      --population-csv data_raw/abs_sa2_population_2023.csv \
      --min-pop 10000

Outputs
-------
- ``outputs/tables/reiwa_wayback_history.csv`` by default. Columns:
  ``suburb_slug, suburb_name, month, snapshot_timestamp, median_house_price,
  house_p25, house_p75, median_house_rent, rent_p25, rent_p75, source``.

Notes
-----
- The script throttles requests (default 1s sleep) to stay polite with the
  archive service.
- If a snapshot is missing or the JSON payload lacks price data, the row is
  recorded with NaNs so downstream processes can detect gaps.
"""

from __future__ import annotations

import argparse
import csv
import html
import json
import sys
import time
from collections import defaultdict
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Iterable, Iterator

import pandas as pd
import requests

from src.config import OUT_DIR


WAYBACK_AVAILABLE = "https://web.archive.org/wayback/available"
SUBURB_URL_TEMPLATE = "https://prpub.reiwa.com.au/suburb/{slug}/"


@dataclass
class PriceSnapshot:
    suburb_slug: str
    suburb_name: str
    month: pd.Timestamp
    snapshot_ts: str | None
    median_house_price: float | None
    house_p25: float | None
    house_p75: float | None
    median_house_rent: float | None
    rent_p25: float | None
    rent_p75: float | None
    source_url: str | None


def _iter_months(start: pd.Timestamp, end: pd.Timestamp) -> Iterator[pd.Timestamp]:
    month = pd.Timestamp(start.year, start.month, 1)
    limit = pd.Timestamp(end.year, end.month, 1)
    while month <= limit:
        yield month
        month = (month + pd.offsets.MonthBegin(1))


def _wayback_snapshot(url: str, when: pd.Timestamp, session: requests.Session, retries: int = 3) -> tuple[str | None, str | None]:
    ts = when.strftime("%Y%m%d")
    attempt = 0
    while attempt <= retries:
        try:
            resp = session.get(
                WAYBACK_AVAILABLE,
                params={"url": url, "timestamp": ts},
                timeout=15,
            )
            resp.raise_for_status()
            break
        except requests.HTTPError:
            status = resp.status_code if 'resp' in locals() else None
            if status in (404, 500):
                return None, None
            if status in (429, 503) and attempt < retries:
                time.sleep(2 ** attempt)
                attempt += 1
                continue
            raise
        except requests.RequestException:
            if attempt < retries:
                time.sleep(2 ** attempt)
                attempt += 1
                continue
            raise
    data = resp.json()
    snap = data.get("archived_snapshots", {}).get("closest")
    if not snap or not snap.get("available"):
        return None, None
    return snap.get("url"), snap.get("timestamp")


def _parse_price_payload(html_text: str) -> dict[str, float | None]:
    # Find the React data-props payload containing SuburbPriceData
    for marker in ("data-props=", "data-props='"):
        start = html_text.find(marker)
        if start == -1:
            continue
        # naive scan forward until matching quote
        quote = html_text[start + len(marker)]
        if quote not in {'"', "'"}:
            continue
        end = html_text.find(quote, start + len(marker) + 1)
        if end == -1:
            continue
        raw = html_text[start + len(marker) + 1 : end]
        decoded = html.unescape(raw)
        if "SuburbPriceData" not in decoded:
            continue
        try:
            payload = json.loads(decoded)
        except json.JSONDecodeError:
            # fix stray newlines and retry
            cleaned = decoded.replace("\r\n", " ")
            payload = json.loads(cleaned)
        price_data = payload.get("data", {}).get("SuburbPriceData", {})
        if price_data:
            return {
                "median_house_price": _to_float(price_data.get("MedianHouseSalePrice")),
                "house_p25": _to_float(price_data.get("HouseSalePriceLowerQuartile")),
                "house_p75": _to_float(price_data.get("HouseSalePriceUpperQuartile")),
                "median_house_rent": _to_float(price_data.get("MedianHouseRentPrice")),
                "rent_p25": _to_float(price_data.get("HouseRentPriceLowerQuartile")),
                "rent_p75": _to_float(price_data.get("HouseRentPriceUpperQuartile")),
            }
    return {}


def _to_float(val) -> float | None:
    if val in (None, "", "NA"):
        return None
    try:
        return float(val)
    except (TypeError, ValueError):
        return None


def _load_suburbs(path: Path) -> pd.DataFrame:
    df = pd.read_csv(path, dtype=str).fillna("")
    df = df[df["state"].str.upper().eq("WA")]
    df["suburb_slug"] = df["suburb_slug"].str.strip().str.lower()
    return df.drop_duplicates(subset=["suburb_slug"])


def _load_population(pop_path: Path) -> pd.DataFrame:
    if not pop_path.exists():
        raise SystemExit(
            f"Population CSV not found at {pop_path}. Provide --population-csv or create a file with 'sa2_code,population'."
        )
    df = pd.read_csv(pop_path)
    # normalise column names
    cols = {c.lower(): c for c in df.columns}
    sa2_col = cols.get("sa2_code") or cols.get("sa2")
    pop_col = cols.get("population") or cols.get("pop") or cols.get("erp_2023")
    if not sa2_col or not pop_col:
        raise SystemExit(
            "Population CSV must contain columns 'sa2_code' and 'population'."
        )
    out = df[[sa2_col, pop_col]].copy()
    out.columns = ["sa2_code", "population"]
    out["sa2_code"] = out["sa2_code"].astype(str)
    out["population"] = pd.to_numeric(out["population"], errors="coerce")
    return out.dropna(subset=["population"])


def _estimate_suburb_population(
    suburbs: pd.DataFrame,
    sal_to_sa2_path: Path,
    population: pd.DataFrame,
) -> pd.DataFrame:
    map_df = pd.read_csv(sal_to_sa2_path, dtype=str)
    map_df["allocation_ratio"] = pd.to_numeric(map_df.get("allocation_ratio", 1.0), errors="coerce").fillna(1.0)
    map_df["suburb_slug"] = map_df["ssc_name"].str.strip().str.lower()
    merged = (
        suburbs.merge(map_df[["suburb_slug", "sa2_code", "allocation_ratio"]], on="suburb_slug", how="left")
        .merge(population, on="sa2_code", how="left")
    )
    merged["weighted_pop"] = merged["population"] * merged["allocation_ratio"].fillna(1.0)
    pop_agg = merged.groupby(["suburb_slug", "suburb_name"], as_index=False)["weighted_pop"].sum()
    pop_agg.rename(columns={"weighted_pop": "estimated_population"}, inplace=True)
    return suburbs.merge(pop_agg, on=["suburb_slug", "suburb_name"], how="left")


def fetch_history(
    suburbs: Iterable[tuple[str, str]],
    months: Iterable[pd.Timestamp],
    session: requests.Session,
    sleep: float,
) -> Iterator[PriceSnapshot]:
    for slug, name in suburbs:
        base_url = SUBURB_URL_TEMPLATE.format(slug=slug)
        for month in months:
            snapshot_url, ts = _wayback_snapshot(base_url, month + pd.offsets.MonthEnd(0), session)
            if not snapshot_url:
                yield PriceSnapshot(slug, name, month, None, None, None, None, None, None, None, None)
                continue
            try:
                html_text = session.get(snapshot_url, timeout=30).text
            except requests.RequestException:
                yield PriceSnapshot(slug, name, month, ts, None, None, None, None, None, None, snapshot_url)
                time.sleep(sleep)
                continue
            data = _parse_price_payload(html_text)
            yield PriceSnapshot(
                suburb_slug=slug,
                suburb_name=name,
                month=month,
                snapshot_ts=ts,
                median_house_price=data.get("median_house_price"),
                house_p25=data.get("house_p25"),
                house_p75=data.get("house_p75"),
                median_house_rent=data.get("median_house_rent"),
                rent_p25=data.get("rent_p25"),
                rent_p75=data.get("rent_p75"),
                source_url=snapshot_url,
            )
            time.sleep(sleep)


def main(argv: list[str] | None = None) -> None:
    ap = argparse.ArgumentParser(description="Backfill REIWA suburb medians from web archives")
    ap.add_argument("--start", required=True, help="YYYY-MM of first month to fetch (inclusive)")
    ap.add_argument("--end", required=True, help="YYYY-MM of final month to fetch (inclusive)")
    ap.add_argument("--suburbs-csv", type=Path, default=Path("data_raw/reiwa_suburbs.csv"))
    ap.add_argument("--population-csv", type=Path, required=True,
                    help="CSV mapping sa2_code → population (latest year)")
    ap.add_argument("--sal-to-sa2", type=Path, default=Path("data_raw/ssc_to_sa2_2021.csv"))
    ap.add_argument("--min-pop", type=float, default=10000.0,
                    help="Minimum estimated suburb population")
    ap.add_argument("--sleep", type=float, default=1.0,
                    help="Seconds to sleep between archive requests")
    ap.add_argument("--output", type=Path, default=OUT_DIR / "tables" / "reiwa_wayback_history.csv")
    args = ap.parse_args(argv)

    start = pd.Timestamp(args.start + "-01")
    end = pd.Timestamp(args.end + "-01")
    if end < start:
        raise SystemExit("--end must be >= --start")

    suburbs = _load_suburbs(args.suburbs_csv)
    population = _load_population(args.population_csv)
    suburbs = _estimate_suburb_population(suburbs, args.sal_to_sa2, population)
    if suburbs["estimated_population"].isna().all():
        raise SystemExit("Could not match suburb population; check mapping files.")
    target_suburbs = (
        suburbs[suburbs["estimated_population"].fillna(0) >= args.min_pop]
        [["suburb_slug", "suburb_name"]]
        .sort_values("suburb_slug")
        .itertuples(index=False, name=None)
    )

    months = list(_iter_months(start, end))
    session = requests.Session()

    records: list[PriceSnapshot] = []
    for slug, name in target_suburbs:
        for snap in fetch_history([(slug, name)], months, session, args.sleep):
            records.append(snap)

    if not records:
        print("No snapshots retrieved", file=sys.stderr)
        return

    out_df = pd.DataFrame([r.__dict__ for r in records])
    args.output.parent.mkdir(parents=True, exist_ok=True)
    out_df.to_csv(args.output, index=False)
    print(f"Wrote {len(out_df)} rows → {args.output}")


if __name__ == "__main__":
    main()
